name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ master, main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ master, main ]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4'

      - name: Setup Project Dependencies
        working-directory: ./security-scan-dashboard
        run: |
          # Create minimal package.json
          echo '{
            "name": "security-scan-dashboard",
            "version": "1.0.0",
            "private": true,
            "dependencies": {
              "@azure/msal-browser": "2.38.0",
              "@azure/msal-react": "1.5.13",
              "@fluentui/react-components": "9.30.0",
              "@microsoft/applicationinsights-web": "3.0.5",
              "@microsoft/applicationinsights-react-js": "3.4.3",
              "ajv": "8.12.0",
              "ajv-keywords": "5.1.0",
              "react": "18.2.0",
              "react-dom": "18.2.0",
              "react-router-dom": "6.22.0",
              "react-scripts": "5.0.1"
            },
            "devDependencies": {
              "@babel/core": "7.23.9",
              "@babel/preset-react": "7.23.3",
              "@babel/preset-env": "7.23.3",
              "@babel/plugin-proposal-private-property-in-object": "7.21.11",
              "@types/react": "18.2.0",
              "@types/react-dom": "18.2.0",
              "typescript": "4.9.5"
            },
            "scripts": {
              "start": "react-scripts start",
              "build": "react-scripts build"
            }
          }' > package.json
          
          # Create .npmrc
          echo "legacy-peer-deps=true
          strict-peer-dependencies=false
          auto-install-peers=true" > .npmrc
          
          # Create telemetryService.js in services directory
          mkdir -p src/services
          echo 'import { ApplicationInsights } from "@microsoft/applicationinsights-web";

          const appInsights = new ApplicationInsights({
            config: {
              connectionString: process.env.REACT_APP_APPINSIGHTS_CONNECTION_STRING,
              enableAutoRouteTracking: true
            }
          });

          appInsights.loadAppInsights();
          appInsights.trackPageView();

          export const trackEvent = (name, properties) => {
            appInsights.trackEvent({ name, properties });
          };

          export const trackException = (error, properties) => {
            appInsights.trackException({ error, properties });
          };

          export default appInsights;' > src/services/telemetryService.js

      - name: Install Dependencies
        working-directory: ./security-scan-dashboard
        run: |
          # Clean install
          rm -rf node_modules package-lock.json
          
          echo "Installing dependencies..."
          npm install --legacy-peer-deps
          
          echo "Verifying installations..."
          npm list @microsoft/applicationinsights-web || echo "Application Insights not found"

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          REACT_APP_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          REACT_APP_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
          REACT_APP_APPINSIGHTS_CONNECTION_STRING: ${{ secrets.REACT_APP_APPINSIGHTS_CONNECTION_STRING }}
          CI: false
          GENERATE_SOURCEMAP: false
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_ROCK_099DB441E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "security-scan-dashboard"
          api_location: "SecurityScanFunction"
          output_location: "build"
          app_build_command: |
            npm install --legacy-peer-deps
            CI=false GENERATE_SOURCEMAP=false npm run build

      - name: Log Build Status
        if: always()
        working-directory: ./security-scan-dashboard
        run: |
          echo "Directory structure:"
          ls -la
          echo "Services directory:"
          ls -la src/services || echo "Services directory not found"
          echo "Dependencies:"
          npm list --depth=0 || echo "Cannot read dependencies"