name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ master, main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ master, main ]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4'

      - name: Debug Directory Structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Repository root contents:"
          ls -la $GITHUB_WORKSPACE

      - name: Prepare Project Structure
        run: |
          # Check if we're in the right directory first
          if [ -d "security-scan-dashboard" ]; then
            cd security-scan-dashboard
            echo "Found security-scan-dashboard directory"
          else
            echo "Creating security-scan-dashboard directory"
            mkdir -p security-scan-dashboard
          fi
          
          # Create standard React app structure
          mkdir -p security-scan-dashboard/src
          mkdir -p security-scan-dashboard/public
          
          # Create necessary files
          touch security-scan-dashboard/src/index.js
          touch security-scan-dashboard/public/index.html
          
          # Copy existing files if they exist
          if [ -d "src" ]; then
            cp -r src/* security-scan-dashboard/src/
          fi
          if [ -d "public" ]; then
            cp -r public/* security-scan-dashboard/public/
          fi
          
          # Create package.json if it doesn't exist
          if [ ! -f "security-scan-dashboard/package.json" ]; then
            echo '{
              "name": "security-scan-dashboard",
              "version": "1.0.0",
              "private": true,
              "dependencies": {
                "@azure/msal-browser": "^2.39.0",
                "@azure/msal-react": "^1.5.13",
                "@fluentui/react-components": "^9.55.1",
                "@fluentui/react-icons": "^2.0.261",
                "@microsoft/applicationinsights-web": "^3.3.3",
                "@microsoft/signalr": "^7.0.14",
                "axios": "^1.7.7",
                "react": "^18.2.0",
                "react-dom": "^18.2.0",
                "react-router-dom": "^6.22.0",
                "react-scripts": "5.0.1",
                "recharts": "^2.13.0"
              },
              "scripts": {
                "start": "react-scripts start",
                "build": "react-scripts build",
                "test": "react-scripts test",
                "eject": "react-scripts eject"
              }
            }' > security-scan-dashboard/package.json
          fi
          
          # Create .npmrc
          echo "legacy-peer-deps=true
          strict-peer-dependencies=false" > security-scan-dashboard/.npmrc
          
          echo "Final directory structure:"
          ls -la security-scan-dashboard

      - name: Install Dependencies
        working-directory: ./security-scan-dashboard
        run: |
          npm install --legacy-peer-deps

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          REACT_APP_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
          REACT_APP_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
          NODE_OPTIONS: "--max-old-space-size=4096"
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_ROCK_099DB441E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "security-scan-dashboard"
          api_location: "SecurityScanFunction"
          output_location: "build"
          app_build_command: |
            npm install --legacy-peer-deps
            npm run build

      - name: Log Build Results
        if: always()
        run: |
          echo "Final directory structure:"
          ls -la
          echo "security-scan-dashboard contents:"
          ls -la security-scan-dashboard || echo "Directory not found"
          echo "Build directory:"
          ls -la security-scan-dashboard/build || echo "Build directory not found"